/*
 * File: app/store/PreceptorDataStore.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pawu.store.PreceptorDataStore', {
    extend: 'Ext.data.Store',

    requires: [
        'pawu.model.PreceptorData',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.util.Sorter'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'pawu.model.PreceptorData',
            remoteSort: true,
            storeId: 'PreceptorDataStore',
            pageSize: 10,
            proxy: {
                type: 'ajax',
                url: '/wu/pawstest/app/store/preceptordata.json',
                reader: {
                    type: 'json',
                    root: 'items'
                }
            },
            sorters: {
                property: 'lastname'
            }
        }, cfg)]);
    }
});