/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pawu.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    html: '<div id=wuheader>\r\n<a href="http://www.westernu.edu" target="_new" id="wulogo" title="Western University of Health Sciences" alt="Western University of Health Sciences">\r\n<img src="http://jprod.westernu.edu/cloud/sencha/wu_logo.png" alt="Western University of Health Sciences"/></a>\r\n<h1 class="wuheader">Physician Assistant Program - Student Rotations Management</h1>\r\n</div>'
                },
                {
                    xtype: 'tabpanel',
                    height: 700,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'preceptorpanel',
                            cls: 'tabstyle',
                            title: 'Data Management',
                            tabConfig: {
                                xtype: 'tab',
                                cls: 'tabstyle'
                            }
                        },
                        {
                            xtype: 'preceptorpanel',
                            title: 'Rotations Management'
                        },
                        {
                            xtype: 'preceptorform',
                            title: 'Lottery Management'
                        },
                        {
                            xtype: 'panel',
                            title: 'Help Videos'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});