/*
 * File: app/view/PreceptorDiscipline.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pawu.view.PreceptorDiscipline', {
    extend: 'Ext.window.Window',
    alias: 'widget.preceptordiscipline',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    height: 250,
    width: 550,
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Preceptor ID',
                            name: 'pid'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Preceptor Discp ID',
                            name: 'precdiscid'
                        },
                        {
                            xtype: 'combobox',
                            width: 400,
                            fieldLabel: 'Discipline ID',
                            name: 'discid',
                            displayField: 'name',
                            store: 'PreceptorComboStore',
                            valueField: 'discid'
                        },
                        {
                            xtype: 'button',
                            itemId: 'mybutton6',
                            text: 'Save'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});