/*
 * File: app/view/PreceptorForm.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pawu.view.PreceptorForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.preceptorform',

    requires: [
        'Ext.form.FieldContainer',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.Label',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.TextItem'
    ],

    frame: true,
    height: 610,
    itemId: 'PreceptorForm',
    width: 700,
    autoScroll: true,
    bodyBorder: false,
    bodyPadding: 10,
    title: 'Preceptor Insert / Update',
    titleCollapse: false,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            defaults: {
                labelWidth: '180'
            },
            items: [
                {
                    xtype: 'fieldcontainer',
                    height: 250,
                    fieldLabel: 'Label',
                    hideLabel: true,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            flex: 1.5,
                            title: 'Directory Information',
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    height: 20,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 2,
                                            fieldLabel: 'First Name',
                                            name: 'firstname'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            fieldLabel: 'M.I.',
                                            labelAlign: 'right',
                                            labelWidth: 60,
                                            name: 'middlename'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Last Name',
                                    name: 'lastname'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Title',
                                    name: 'title'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    height: 20,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 2,
                                            fieldLabel: 'Degree',
                                            name: 'degree'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            fieldLabel: 'Prefix',
                                            labelAlign: 'right',
                                            labelWidth: 60,
                                            name: 'pref'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Address 1',
                                    name: 'address1'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Address 2:',
                                    name: 'address2'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'City',
                                    name: 'city'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            fieldLabel: 'State',
                                            name: 'state'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            fieldLabel: 'Zip',
                                            labelAlign: 'right',
                                            labelWidth: 50,
                                            name: 'zip'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            height: 288,
                            defaults: {
                                labelWidth: 130,
                                height: 20
                            },
                            title: 'Details',
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                defaultMargins: {
                                    top: 0,
                                    right: 0,
                                    bottom: 0,
                                    left: 0
                                }
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    height: 20,
                                    fieldLabel: 'Is Active',
                                    name: 'isactive'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Affiliation Year'
                                },
                                {
                                    xtype: 'label'
                                },
                                {
                                    xtype: 'datefield',
                                    fieldLabel: 'Initial Appt. Dt:',
                                    name: 'initial_apptdate',
                                    emptyText: 'mm/dd/yyyy'
                                },
                                {
                                    xtype: 'datefield',
                                    fieldLabel: 'Most Recent Appt Dt',
                                    name: 'mostrecent_apptdate'
                                },
                                {
                                    xtype: 'datefield',
                                    fieldLabel: 'Re-Credentialing Dt:',
                                    name: 'recredentialing_date'
                                },
                                {
                                    xtype: 'label'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 1,
                                    height: 120,
                                    width: 400,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'mybutton',
                                            text: 'Submit Form'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'Reset'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    title: 'Contact Information',
                    layout: {
                        type: 'vbox',
                        align: 'stretch',
                        padding: 5
                    },
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            flex: 1,
                            height: 20,
                            width: 400,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Contact Name',
                                    name: 'contact'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: 'Email',
                                    labelAlign: 'right',
                                    name: 'email'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            flex: 1,
                            height: 20,
                            width: 400,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: 'Phone1',
                                    name: 'phone1'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: 'Phone2',
                                    labelAlign: 'right',
                                    name: 'phone2'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: 'Fax',
                                    labelAlign: 'right',
                                    name: 'fax'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    height: 120,
                    fieldLabel: 'Label',
                    hideLabel: true,
                    items: [
                        {
                            xtype: 'fieldset',
                            title: 'General Information',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'textareafield',
                                    fieldLabel: 'Note',
                                    name: 'note'
                                },
                                {
                                    xtype: 'textareafield',
                                    fieldLabel: 'Special Instructions',
                                    name: 'special'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            iconAlign: 'right',
                            iconCls: 'user_add',
                            text: 'Add New'
                        },
                        {
                            xtype: 'tbtext',
                            text: 'My Text'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});