/*
 * File: app/model/PreceptorData.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('pawu.model.PreceptorData', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.association.HasMany',
        'Ext.data.proxy.Rest'
    ],
    uses: [
        'pawu.model.Hospitals',
        'pawu.model.DisciplineData'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'isactive'
        },
        {
            name: 'affil_year'
        },
        {
            name: 'lastname'
        },
        {
            name: 'middlename'
        },
        {
            name: 'firstname'
        },
        {
            name: 'title'
        },
        {
            name: 'degree'
        },
        {
            name: 'contact'
        },
        {
            name: 'pref'
        },
        {
            name: 'email'
        },
        {
            name: 'address1'
        },
        {
            name: 'address2'
        },
        {
            name: 'city'
        },
        {
            name: 'state'
        },
        {
            name: 'zip'
        },
        {
            name: 'phone1'
        },
        {
            name: 'phone2'
        },
        {
            name: 'fax'
        },
        {
            name: 'note'
        },
        {
            name: 'campus'
        },
        {
            name: 'special'
        },
        {
            name: 'initial_apptdate'
        },
        {
            dateFormat: 'm/d/Y',
            name: 'mostrecent_apptdate',
            type: 'date'
        },
        {
            name: 'recredentialing_date'
        },
        {
            name: 'faculty_appointment'
        },
        {
            name: 'precepdiscp'
        },
        {
            name: 'hospitals'
        }
    ],

    hasMany: [
        {
            model: 'pawu.model.Hospitals',
            name: 'hospitals'
        },
        {
            model: 'pawu.model.DisciplineData',
            primaryKey: 'precdiscid',
            foreignKey: 'pid',
            name: 'disciplines'
        }
    ]
});